INSERT INTO [Make] ([Name]) VALUES (N'Acura');
INSERT INTO [Make] ([Name]) VALUES (N'Alfa Romeo');
INSERT INTO [Make] ([Name]) VALUES (N'AM General');
INSERT INTO [Make] ([Name]) VALUES (N'American Motors (AMC)');
INSERT INTO [Make] ([Name]) VALUES (N'Aston Martin');
INSERT INTO [Make] ([Name]) VALUES (N'Audi');
INSERT INTO [Make] ([Name]) VALUES (N'Bentley');
INSERT INTO [Make] ([Name]) VALUES (N'BMW');
INSERT INTO [Make] ([Name]) VALUES (N'Buick');
INSERT INTO [Make] ([Name]) VALUES (N'Cadillac');
INSERT INTO [Make] ([Name]) VALUES (N'Chevrolet');
INSERT INTO [Make] ([Name]) VALUES (N'Chrysler');
INSERT INTO [Make] ([Name]) VALUES (N'Daewoo');
INSERT INTO [Make] ([Name]) VALUES (N'Daihatsu');
INSERT INTO [Make] ([Name]) VALUES (N'Datsun');
INSERT INTO [Make] ([Name]) VALUES (N'Dodge');
INSERT INTO [Make] ([Name]) VALUES (N'Eagle');
INSERT INTO [Make] ([Name]) VALUES (N'Ferrari');
INSERT INTO [Make] ([Name]) VALUES (N'FIAT');
INSERT INTO [Make] ([Name]) VALUES (N'Fisker');
INSERT INTO [Make] ([Name]) VALUES (N'Ford');
INSERT INTO [Make] ([Name]) VALUES (N'Genesis');
INSERT INTO [Make] ([Name]) VALUES (N'Geo');
INSERT INTO [Make] ([Name]) VALUES (N'GMC');
INSERT INTO [Make] ([Name]) VALUES (N'Honda');
INSERT INTO [Make] ([Name]) VALUES (N'HUMMER');
INSERT INTO [Make] ([Name]) VALUES (N'Hyundai');
INSERT INTO [Make] ([Name]) VALUES (N'INFINITI');
INSERT INTO [Make] ([Name]) VALUES (N'Isuzu');
INSERT INTO [Make] ([Name]) VALUES (N'Jaguar');
INSERT INTO [Make] ([Name]) VALUES (N'Jeep');
INSERT INTO [Make] ([Name]) VALUES (N'Kia');
INSERT INTO [Make] ([Name]) VALUES (N'Lamborghini');
INSERT INTO [Make] ([Name]) VALUES (N'Land Rover');
INSERT INTO [Make] ([Name]) VALUES (N'Lexus');
INSERT INTO [Make] ([Name]) VALUES (N'Lincoln');
INSERT INTO [Make] ([Name]) VALUES (N'Lotus');
INSERT INTO [Make] ([Name]) VALUES (N'Maserati');
INSERT INTO [Make] ([Name]) VALUES (N'Maybach');
INSERT INTO [Make] ([Name]) VALUES (N'Mazda');
INSERT INTO [Make] ([Name]) VALUES (N'McLaren');
INSERT INTO [Make] ([Name]) VALUES (N'Mercedes-Benz');
INSERT INTO [Make] ([Name]) VALUES (N'Mercury');
INSERT INTO [Make] ([Name]) VALUES (N'Merkur');
INSERT INTO [Make] ([Name]) VALUES (N'MINI');
INSERT INTO [Make] ([Name]) VALUES (N'Mitsubishi');
INSERT INTO [Make] ([Name]) VALUES (N'Nissan');
INSERT INTO [Make] ([Name]) VALUES (N'Oldsmobile');
INSERT INTO [Make] ([Name]) VALUES (N'Panoz');
INSERT INTO [Make] ([Name]) VALUES (N'Peugeot');
INSERT INTO [Make] ([Name]) VALUES (N'Plymouth');
INSERT INTO [Make] ([Name]) VALUES (N'Pontiac');
INSERT INTO [Make] ([Name]) VALUES (N'Porsche');
INSERT INTO [Make] ([Name]) VALUES (N'Ram');
INSERT INTO [Make] ([Name]) VALUES (N'Renault');
INSERT INTO [Make] ([Name]) VALUES (N'Rolls-Royce');
INSERT INTO [Make] ([Name]) VALUES (N'Saab');
INSERT INTO [Make] ([Name]) VALUES (N'Saturn');
INSERT INTO [Make] ([Name]) VALUES (N'Scion');
INSERT INTO [Make] ([Name]) VALUES (N'smart');
INSERT INTO [Make] ([Name]) VALUES (N'Sterling');
INSERT INTO [Make] ([Name]) VALUES (N'Subaru');
INSERT INTO [Make] ([Name]) VALUES (N'Suzuki');
INSERT INTO [Make] ([Name]) VALUES (N'Tesla');
INSERT INTO [Make] ([Name]) VALUES (N'Toyota');
INSERT INTO [Make] ([Name]) VALUES (N'Volkswagen');
INSERT INTO [Make] ([Name]) VALUES (N'Volvo');
INSERT INTO [Make] ([Name]) VALUES (N'Yugo');


INSERT INTO [Class] ([Name], [Description]) VALUES (N'SUV', N'Sports Utility Vehicle generally has a 4 wheel drive, meaning engine power flows to all wheels. SUVs stand tall with high ground clearance, making it suitable for all kinds of terrain. It maybe a 5-7 seater depending on the length of the vehicle.');
INSERT INTO [Class] ([Name], [Description]) VALUES (N'MPV', N'Multi Purpose Vehicle. As the name suggests, they mostly accommodate 7–8 people. They stand tall with good ground clearance but need not necessarily be as tall as an SUV.');
INSERT INTO [Class] ([Name], [Description]) VALUES (N'Hatchback', N'do not have a stretched boot. Usually less than 4 metres in length, these vehicles are the most common in developing countries. They are much smaller in height compared to the SUVs. They are mostly used to carry 4–5 people.');
INSERT INTO [Class] ([Name], [Description]) VALUES (N'Sedan', N'Sedans are extended forms of hatchback cars. They have a rear boot that projects out of the body. They are longer than 4 metres and carry 4–5 people. ');
INSERT INTO [Class] ([Name], [Description]) VALUES (N'Luxury', N'Mostly known for their luxury features inside the vehicle. They have features such as heated seats, leather seats, ample leg room, brilliant suspension for smooth ride, top quality music system, and many more.');
INSERT INTO [Class] ([Name], [Description]) VALUES (N'Coupé', N'Has a fixed-roof body style that is shorter than a sedan of the same model. Often, a coupé will only seat two people and have two doors.');
INSERT INTO [Class] ([Name], [Description]) VALUES (N'Sport compact', N'A high-performance version of a compact car or a subcompact car.');
INSERT INTO [Class] ([Name], [Description]) VALUES (N'Sport', N'A small, usually two-seater, two-door automobile designed for spirited performance and nimble handling.');
INSERT INTO [Class] ([Name], [Description]) VALUES (N'Roadster', N'An open two-seat car with emphasis on sporting appearance or character.');
INSERT INTO [Class] ([Name], [Description]) VALUES (N'Subcompact', N'A car smaller than a compact car.');
INSERT INTO [Class] ([Name], [Description]) VALUES (N'Compact', N'A classification of cars that are larger than a subcompact car but smaller than a mid-size car.');
INSERT INTO [Class] ([Name], [Description]) VALUES (N'GT', N'A grand tourer (GT) is a performance and luxury automobile capable of high speed and long-distance driving.');
INSERT INTO [Class] ([Name], [Description]) VALUES (N'Sports sedan', N'A sports sedan oris a sedan automobilethat is designed to look and feel sporty, offering the motorist more connection with the driving experience, while providing the comfort and amenities expected of a luxury sedan.');


INSERT INTO [Transmission] ([Type], [Description]) VALUES (N'Manual (MT)', N'Requires manual gear selection by the driver.');
INSERT INTO [Transmission] ([Type], [Description]) VALUES (N'Automatic (AT)', N'Automatically controls the clutching and transmission.');
INSERT INTO [Transmission] ([Type], [Description]) VALUES (N'Continuously Variable (CVT)', N'An automatic transmission style favored by manufacturers for its lower production cost, ability to achieve better fuel economy and its seamless or uninterrupted transmission of torque between the engine and driving wheels.');
INSERT INTO [Transmission] ([Type], [Description]) VALUES (N'Dual-Clutch (DCT)', N'A manual transmission that changes gears for you, only much faster, with the benefit of being an almost uninterrupted transmission of torque between the engine and the driving wheels. DCTs allow shifting manually or automatically as required.');
INSERT INTO [Transmission] ([Type], [Description]) VALUES (N'Single-Clutch (SCT)', N'A manual transmission that shifts gears on your behalf. The transmission’s ratios are arranged sequentially and may only be shifted in numerical order.');
INSERT INTO [Transmission] ([Type], [Description]) VALUES (N'Automated Manual (AMT)', N'The AMT is like a manual transmission that does away with the clutch and lever. But, like the traditional manual gearbox, takes time to disengage and re-engage the delivery of torque from the engine to the driven wheels while the ratio is changed.');
INSERT INTO [Transmission] ([Type], [Description]) VALUES (N'Infinitely variable (IVT)', N'A specific type of CVT that includes not only an infinite number of gear ratios, but an "infinite" range as well.');
INSERT INTO [Transmission] ([Type], [Description]) VALUES (N'Electric variable (EVT)', N'Combines a transmission with an electric motor to provide the illusion of a single CVT.');


INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (1, 6, N'CL', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (1, 5, N'ILX', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (1, 7, N'Integra', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (1, 5, N'Legend', 6);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (1, 5, N'MDX', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (1, 8, N'NSX', 4);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (1, 1, N'RDX', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (1, 4, N'RL', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (1, 5, N'RLX', 4);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (1, 5, N'RSX', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (1, 1, N'SLX', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (1, 5, N'TL', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (1, 4, N'TLX', 4);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (1, 5, N'TSX', 6);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (1, 4, N'Vigor', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (1, 5, N'ZDX', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (2, 4, N'164 Series', 1);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (2, 8, N'4C', 4);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (2, 6, N'4C Coupe', 4);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (2, 8, N'4C Spider', 4);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (2, 4, N'Giulia', 1);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (2, 4, N'Giulia Quadrifoglio', 1);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (2, 8, N'GTV-6', 1);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (2, 4, N'Milano', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (2, 9, N'Spider', 1);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (2, 9, N'Spider Veloce', 1);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (2, 1, N'Stelvio', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (3, 1, N'Hummer', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (4, 10, N'Alliance', 6);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (4, 11, N'Concord', 1);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (4, 11, N'Eagle', 1);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (4, 3, N'Encore', 1);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (4, 10, N'Spirit', 1)
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (4, 11, N'Sport Wagon', 1);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (5, 12, N'DB11', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (5, 12, N'DB7', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (5, 12, N'DB9', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (5, 12, N'DBS', 1);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (5, 13, N'Rapide', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (5, 12, N'Vanquish', 6);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (5, 6, N'Vantage', 1);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (5, 12, N'Virage', 1);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 5, N'100', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 5, N'200', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 11, N'4000', 1);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 5, N'5000', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 11, N'80', 6);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 11, N'90', 6);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 11, N'A3', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 11, N'A3 Cabriolet', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 4, N'A3 e-tron', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 4, N'A3 Sedan', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 8, N'A3 Sportback e-tron', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 11, N'A4', 1);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 11, N'A4 allroad', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 11, N'A5', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 11, N'A5 Cabriolet', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 6, N'A5 Coupe', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 11, N'A5 Sportback', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 11, N'A6', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 5, N'A7', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 5, N'A8', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 11, N'Q3', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 11, N'Q5', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 1, N'Q7', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 8, N'R8', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 6, N'R8 Coupe', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 12, N'R8 Spyder', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (1, 4, N'R5', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 8, N'RS 6 quattro', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 8, N'RS', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 11, N'S3', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 11, N'S4', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 12, N'S5', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 5, N'S5 Cabriolet', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 6, N'S5 Coupe', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 8, N'S5 Sportback', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 11, N'S6', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 7, N'S7', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 4, N'S8', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 7, N'S8 Plus', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 1, N'SQ5', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 7, N'TT', 4);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (6, 4, N'V8 Quattro', 1);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (7, 5, N'Arnage', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (7, 12, N'Azure', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (7, 1, N'Bentayga', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (7, 4, N'Brooklands', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (7, 4, N'Continental', 1);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (7, 4, N'Flying Spur', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (7, 5, N'Mulsanne', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 5, N'1 Series', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 11, N'2 Series', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 5, N'3 Series', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 12, N'3 Series Gran Turismo', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 6, N'4 Series', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 5, N'5 Series', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 12, N'5 Series Gran Turismo', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 12, N'6 Series', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 12, N'7 Series', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 12, N'8 Series', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 11, N'i3', 8);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 8, N'i8', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 6, N'M2', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 5, N'M3', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 7, N'M4', 1);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 13, N'M5', 1);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 12, N'M6', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 1, N'X1', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 1, N'X3', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 1, N'X4', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 5, N'X5', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 5, N'X6', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 9, N'Z3', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 9, N'Z4', 2);
INSERT INTO [Model] ([MakeId], [ClassId], [Name], [TransmissionId]) VALUES (8, 9, N'Z8', 2);


INSERT INTO [Color] ([Name], [Code]) VALUES (N'Super White II', N'#ffffff');
INSERT INTO [Color] ([Name], [Code]) VALUES (N'White Pearl Crystal Shine', N'#efefef');
INSERT INTO [Color] ([Name], [Code]) VALUES (N'Silver Metalic', N'#d7dde0');
INSERT INTO [Color] ([Name], [Code]) VALUES (N'Gray Metalic', N'#737b7a');
INSERT INTO [Color] ([Name], [Code]) VALUES (N'Black Mica', N'#091f22');
INSERT INTO [Color] ([Name], [Code]) VALUES (N'Red Mica Metalic', N'#920c25');
INSERT INTO [Color] ([Name], [Code]) VALUES (N'Beige Metalic', N'#ccc9b0');
INSERT INTO [Color] ([Name], [Code]) VALUES (N' Diamond White', N'#f5f4ef');
INSERT INTO [Color] ([Name], [Code]) VALUES (N'Bronze Mica Metalic', N'#bbb38e');
INSERT INTO [Color] ([Name], [Code]) VALUES (N'Dark Blue Mica Metallic', N'#00448c');
INSERT INTO [Color] ([Name], [Code]) VALUES (N'Yanmer Beige', N'#dec29d');
INSERT INTO [Color] ([Name], [Code]) VALUES (N'Light Blue Mica Metalic', N'#b8c7cb');
INSERT INTO [Color] ([Name], [Code]) VALUES (N'Grey Mica Metalic', N'#5b5c5d');
INSERT INTO [Color] ([Name], [Code]) VALUES (N'Dark Steel Mica', N'#112023');
INSERT INTO [Color] ([Name], [Code]) VALUES (N'Red Mica', N'#7c1a2e');
INSERT INTO [Color] ([Name], [Code]) VALUES (N'Light Yellow Mica Metalic', N'#d1cdc5');
INSERT INTO [Color] ([Name], [Code]) VALUES (N'Dark Blue Mica Metalic', N'#0a2657');


INSERT INTO [Availability] ([Description]) VALUES (N'Available')
INSERT INTO [Availability] ([Description]) VALUES (N'Rented')
INSERT INTO [Availability] ([Description]) VALUES (N'Under Maintenance')


INSERT INTO [UserRole] ([Name], [Description]) VALUES (N'Employee', N'An employee.');
INSERT INTO [UserRole] ([Name], [Description]) VALUES (N'Customer', N'A customer.');
INSERT INTO [UserRole] ([Name], [Description]) VALUES (N'Administrator', N'A sys admin.');
